#!/usr/bin/env sh

# Author : Haruyama kenta

#ypspur-coordinator -p $1 -d /dev/sensors/icart-mini &
#echo "robot parameters [$1] loaded"

sudo chmod 777 /dev/ttyACM0
ypspur-coordinator -p $1 -d /dev/ttyACM0